### ISSUE TITLE
Unable to connect to i.mjh.nz : Max retries exceeded

### ISSUE THREAD

**Issue by Facy5** [matthuisman/samsung-tvplus-for-channels#15]
Hello Matt, after a new install on Docker, I got this error :

```
Error: HTTPSConnectionPool(host='i.mjh.nz', port=443): Max retries exceeded with url: /SamsungTVPlus/.app.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7275cdefcd40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
```
I tried to reinstall the Docker image, but unsuccessfuly.

The full log say :

```
192.168.1.11 - - [28/Oct/2024 22:23:46] "GET / HTTP/1.1" 500 -
----------------------------------------
Exception occurred during processing of request from ('192.168.1.11', 54484)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 196, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/usr/local/lib/python3.12/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 490, in _make_request
    raise new_e
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 615, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 211, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7275cdefcd40>: Failed to establish a new connection: [Errno 101] Network is unreachable
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='i.mjh.nz', port=443): Max retries exceeded with url: /SamsungTVPlus/.app.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7275cdefcd40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/socketserver.py", line 692, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.12/socketserver.py", line 362, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/src/app/./app.py", line 23, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.12/socketserver.py", line 761, in __init__
    self.handle()
  File "/usr/local/lib/python3.12/http/server.py", line 436, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.12/http/server.py", line 424, in handle_one_request

    method()
  File "/usr/src/app/./app.py", line 50, in do_GET
    self._error(e)
  File "/usr/src/app/./app.py", line 48, in do_GET
    routes[func]()
  File "/usr/src/app/./app.py", line 110, in _status
    all_channels = requests.get(APP_URL).json()['regions']
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='i.mjh.nz', port=443): Max retries exceeded with url: /SamsungTVPlus/.app.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7275cdefcd40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
----------------------------------------
```
It's basically a new Docker install, with your image installed for the first time. My connexion get through AdGuard, but even with protection disabled, I got the same result.
Does my local address have to be in HTTPS, or anything else ?

**Comment by matthuisman** [comment]
Suspect your isp blocking i.mjh.nz. try different dns server

**Comment by telnetdoogie** [comment]
`Network is unreachable` suggests to me that the container is unable to reach the internet.
