### ISSUE TITLE
python error - broken pipe

### ISSUE THREAD

**Issue by subasically** [matthuisman/samsung-tvplus-for-channels#19]
I saw someone else posted the same issue in [2021.](https://github.com/matthuisman/samsung-tvplus-for-channels/issues/2)

Issue seems to be back.
```bash
10.10.10.34 - - [07/Nov/2024 17:51:18] "GET /epg.xml HTTP/1.1" 200 -
10.10.10.34 - - [07/Nov/2024 17:51:19] "GET /playlist.m3u8 HTTP/1.1" 200 -
Including channels from regions: ['ca', 'gb', 'us']
10.10.10.34 - - [07/Nov/2024 17:55:51] "GET /playlist.m3u8 HTTP/1.1" 200 -
Including channels from regions: ['ca', 'gb', 'us']
10.10.10.34 - - [07/Nov/2024 17:55:51] "GET /playlist.m3u8 HTTP/1.1" 500 -
----------------------------------------
Exception occurred during processing of request from ('10.10.10.34', 62293)
Traceback (most recent call last):
  File "/usr/src/app/./app.py", line 54, in do_GET
    routes[func]()
  File "/usr/src/app/./app.py", line 125, in _playlist
    self.wfile.write(f'#EXTINF:-1 channel-id="{channel_id}" tvg-id="{key}" tvg-logo="{logo}" group-title="{group}"{chno},{name}\n{url}\n'.encode('utf8'))
  File "/usr/local/lib/python3.12/socketserver.py", line 840, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/socketserver.py", line 692, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.12/socketserver.py", line 362, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/src/app/./app.py", line 24, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.12/socketserver.py", line 761, in __init__
    self.handle()
  File "/usr/local/lib/python3.12/http/server.py", line 436, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.12/http/server.py", line 424, in handle_one_request
    method()
  File "/usr/src/app/./app.py", line 56, in do_GET
    self._error(e)
  File "/usr/src/app/./app.py", line 28, in _error
    self.end_headers()
  File "/usr/local/lib/python3.12/http/server.py", line 538, in end_headers
    self.flush_headers()
  File "/usr/local/lib/python3.12/http/server.py", line 542, in flush_headers
    self.wfile.write(b"".join(self._headers_buffer))
  File "/usr/local/lib/python3.12/socketserver.py", line 840, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------
```

**Comment by matthuisman** [comment]
Maybe it's due to the latest now defaulting to all regions? See if you add
?regions=us helps

**Comment by matthuisman** [comment]
Actually, are you using latest docker from yesterday?

**Comment by matthuisman** [comment]
i meant, are you using the latest container that i pushed yesterday?

**Comment by matthuisman** [comment]
ok thanks. so all fixed after restarting container. ill keep issue closed

**Comment by telnetdoogie** [comment]
I'm having this issue now...

The container appears to do nothing after starting (no log output)

here's my compose:

```yml
samsung-tvplus:
    container_name: samsung-tvplus
    environment:
      - REGIONS=us
    image: matthuisman/samsung-tvplus-for-channels:latest
    ports:         # only needed to get original URLS;
      - 8182:80    # does not need to be exposed.
    restart: unless-stopped
    volumes:
    - /etc/localtime:/etc/localtime:ro
```

Just going to the 'homepage' (http://ip:8182 given the above port config) from my client sits and spins for a LONG time... eventually the page shows up, and I can click around the region links and things appear to load fine.

Here's the error log:

```log
192.168.1.6 - - [10/Nov/2024 13:21:12] "GET / HTTP/1.1" 200 -
192.168.1.6 - - [10/Nov/2024 13:21:12] "GET / HTTP/1.1" 500 -
----------------------------------------
Exception occurred during processing of request from ('192.168.1.6', 51107)
Traceback (most recent call last):
  File "/usr/src/app/./app.py", line 54, in do_GET
    routes[func]()
  File "/usr/src/app/./app.py", line 152, in _status
    self.wfile.write(f'''
  File "/usr/local/lib/python3.12/socketserver.py", line 840, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/socketserver.py", line 692, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.12/socketserver.py", line 362, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/src/app/./app.py", line 24, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.12/socketserver.py", line 761, in __init__
    self.handle()
  File "/usr/local/lib/python3.12/http/server.py", line 436, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.12/http/server.py", line 424, in handle_one_request
    method()
  File "/usr/src/app/./app.py", line 56, in do_GET
    self._error(e)
  File "/usr/src/app/./app.py", line 28, in _error
    self.end_headers()
  File "/usr/local/lib/python3.12/http/server.py", line 538, in end_headers
    self.flush_headers()
  File "/usr/local/lib/python3.12/http/server.py", line 542, in flush_headers
    self.wfile.write(b"".join(self._headers_buffer))
  File "/usr/local/lib/python3.12/socketserver.py", line 840, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------
192.168.1.6 - - [10/Nov/2024 13:21:39] "GET / HTTP/1.1" 200 -
192.168.1.6 - - [10/Nov/2024 13:21:39] "GET / HTTP/1.1" 500 -
----------------------------------------
Exception occurred during processing of request from ('192.168.1.6', 51108)
Traceback (most recent call last):
  File "/usr/src/app/./app.py", line 54, in do_GET
    routes[func]()
  File "/usr/src/app/./app.py", line 173, in _status
    self.wfile.write(f'<li><a href="http://{host}/{PLAYLIST_PATH}?regions={encoded_region}&groups={encoded_group}">{group}</a></li>'.encode('utf8'))
  File "/usr/local/lib/python3.12/socketserver.py", line 840, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/socketserver.py", line 692, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.12/socketserver.py", line 362, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/src/app/./app.py", line 24, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.12/socketserver.py", line 761, in __init__
    self.handle()
  File "/usr/local/lib/python3.12/http/server.py", line 436, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.12/http/server.py", line 424, in handle_one_request
    method()
  File "/usr/src/app/./app.py", line 56, in do_GET
    self._error(e)
  File "/usr/src/app/./app.py", line 28, in _error
    self.end_headers()
  File "/usr/local/lib/python3.12/http/server.py", line 538, in end_headers
    self.flush_headers()
  File "/usr/local/lib/python3.12/http/server.py", line 542, in flush_headers
    self.wfile.write(b"".join(self._headers_buffer))
  File "/usr/local/lib/python3.12/socketserver.py", line 840, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------
192.168.1.6 - - [10/Nov/2024 13:21:43] "GET / HTTP/1.1" 200 -
192.168.1.6 - - [10/Nov/2024 13:21:44] "GET /favicon.ico HTTP/1.1" 200 -
192.168.1.254 - - [10/Nov/2024 13:21:58] "GET / HTTP/1.1" 200 -
192.168.1.254 - - [10/Nov/2024 13:21:58] "GET / HTTP/1.1" 500 -
----------------------------------------
Exception occurred during processing of request from ('192.168.1.254', 56076)
Traceback (most recent call last):
  File "/usr/src/app/./app.py", line 54, in do_GET
    routes[func]()
  File "/usr/src/app/./app.py", line 152, in _status
    self.wfile.write(f'''
  File "/usr/local/lib/python3.12/socketserver.py", line 840, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/socketserver.py", line 692, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.12/socketserver.py", line 362, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/src/app/./app.py", line 24, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.12/socketserver.py", line 761, in __init__
    self.handle()
  File "/usr/local/lib/python3.12/http/server.py", line 436, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.12/http/server.py", line 424, in handle_one_request
    method()
  File "/usr/src/app/./app.py", line 56, in do_GET
    self._error(e)
  File "/usr/src/app/./app.py", line 28, in _error
    self.end_headers()
  File "/usr/local/lib/python3.12/http/server.py", line 538, in end_headers
    self.flush_headers()
  File "/usr/local/lib/python3.12/http/server.py", line 542, in flush_headers
    self.wfile.write(b"".join(self._headers_buffer))
  File "/usr/local/lib/python3.12/socketserver.py", line 840, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------
```

**Comment by telnetdoogie** [comment]
...once the error has occurred, I can link to the m3u8 (adding regions to the url params if I don't want weird output) and the epg (no need for regions here apparently) and things seem to work ok

**Comment by telnetdoogie** [comment]
@matthuisman can we open this Issue back up again?

**Comment by richardk80** [comment]
> @matthuisman can we open this Issue back up again? This latest build is totally broken for me.

I see that you forked my repo, and I noticed that @matthuisman changed some code. I added his changed code to my repo and once I redid my container, it's all working again. Look into my repo to get the latest changes and see if that works for you

**Comment by telnetdoogie** [comment]
@matthuisman I have some updates I will submit as a PR here in the next 30 minutes or so to resolve this.

**Comment by telnetdoogie** [comment]
@richardk80 apologies... I forked the wrong repo... reparented back to this for ease of submitting a PR

**Comment by stewartcampbell** [comment]
I was seeing this error earlier too. I added some debug code to try work out the exact issue, or at least narrow things down. Of course now its working without me changing anything.

I'll leave it running overnight to see if it catches anything, but in case it helps if one of you are still having the issue, here it is:
https://github.com/matthuisman/samsung-tvplus-for-channels/compare/master...stewartcampbell:samsung-tvplus-for-channels:feature/external-dl-logging

Need to set `DEBUG=1` to trigger the logging.

I appreciate there is a PR there to catch these errors, but it would be good to know why they are happening too. Definitely looks like some sort of timeout but other situations are in there too, just in case.

**Comment by matthuisman** [comment]
ive left a few comments on the linked PR.

Its cloudflare issue. But not sure how to get them to fix it...
As I can replicate from browsers on different servers (windows and linux) in different geos

**Comment by matthuisman** [comment]
i havnt switched anything... 
What made you think its using fastly?

**Comment by stewartcampbell** [comment]
In fact, I see now. It appears that responses for the Json have Cloudflare headers, while the responses from the .gz have Fastly headers.
```
=== REQUEST STARTED ===
TIME: 2024-11-12 08:02:54
TIMEOUT (both connect and read): 5s

-- REQUEST DETAILS --
URL: https://i.mjh.nz/SamsungTVPlus/.channels.json
METHOD: GET
SCHEME: https
HOST: i.mjh.nz
PATH: /SamsungTVPlus/.channels.json
QUERY: 
REQUEST HEADERS: {}

-- DNS INFO --
RESOLVED IP: 104.21.88.162
DNS RESOLUTION TIME: 0.026s

-- CONNECTION SUCCESS --
INITIAL CONNECTION TIME: 0.13472723960876465s
TOTAL TIME: 0.215s
ELAPSED TIME: 0.134147s
STATUS CODE: 200
RESPONSE HEADERS: {'Date': 'Tue, 12 Nov 2024 08:02:54 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Last-Modified': 'Tue, 12 Nov 2024 07:32:01 GMT', 'ETag': 'W/"67330471-150957"', 'Expires': 'Tue, 12 Nov 2024 09:01:57 GMT', 'Cache-Control': 'max-age=3600', 'Access-Control-Allow-Origin': '*', 'CF-Cache-Status': 'HIT', 'Age': '57', 'Report-To': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v4?s=m07iJMhI3puu6tjuXf0CuekZUnMnqpj%2Bqwn7VfChwipSgrG0SEUMg038WDtjUBsXjB4fv2RQSRjHwLJfn3DHgJ2Wv3JRnHkfkcV02PbSqpPsiu9aWXpCFIz%2FgA%3D%3D"}],"group":"cf-nel","max_age":604800}', 'NEL': '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}', 'Vary': 'Accept-Encoding', 'Server': 'cloudflare', 'CF-RAY': '8e1500a1e9fd4176-LHR', 'Content-Encoding': 'gzip', 'alt-svc': 'h3=":443"; ma=86400', 'server-timing': 'cfL4;desc="?proto=TCP&rtt=30096&sent=4&recv=6&lost=0&retrans=0&sent_bytes=2824&recv_bytes=786&delivery_rate=100142&cwnd=231&unsent_bytes=0&cid=512054e66894c554&ts=55&x=0"'}
RESPONSE SIZE: 1378647 bytes

=== REQUEST ENDED ===

Including channels from regions: ['at', 'ca', 'ch', 'de', 'es', 'fr', 'gb', 'in', 'it', 'kr', 'us']
192.168.0.201 - - [12/Nov/2024 08:02:54] "GET /playlist.m3u8 HTTP/1.1" 200 -

=== REQUEST STARTED ===
TIME: 2024-11-12 08:03:09
TIMEOUT (both connect and read): 5s

-- REQUEST DETAILS --
URL: https://i.mjh.nz/SamsungTVPlus/all.xml.gz
METHOD: GET
SCHEME: https
HOST: i.mjh.nz
PATH: /SamsungTVPlus/all.xml.gz
QUERY: 
REQUEST HEADERS: {}

-- DNS INFO --
RESOLVED IP: 104.21.88.162
DNS RESOLUTION TIME: 0.028s

-- CONNECTION SUCCESS --
INITIAL CONNECTION TIME: 0.21931767463684082s
TOTAL TIME: 0.219s
ELAPSED TIME: 0.086476s
STATUS CODE: 200
RESPONSE HEADERS: {'Connection': 'keep-alive', 'Content-Length': '1862658', 'Cache-Control': 'max-age=300', 'Content-Security-Policy': "default-src 'none'; style-src 'unsafe-inline'; sandbox", 'Content-Type': 'application/octet-stream', 'ETag': 'W/"128170ecdaceeeba277ec47303bce2c145288ccd32cf7713a5d8fed793701fb8"', 'Strict-Transport-Security': 'max-age=31536000', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'deny', 'X-XSS-Protection': '1; mode=block', 'X-GitHub-Request-Id': '241C:32B3:25B86:2ED27:67330712', 'Accept-Ranges': 'bytes', 'Date': 'Tue, 12 Nov 2024 08:03:09 GMT', 'Via': '1.1 varnish', 'X-Served-By': 'cache-lhr-egll1980034-LHR', 'X-Cache': 'HIT', 'X-Cache-Hits': '0', 'X-Timer': 'S1731398589.264943,VS0,VE1', 'Vary': 'Authorization,Accept-Encoding,Origin', 'Access-Control-Allow-Origin': '*', 'Cross-Origin-Resource-Policy': 'cross-origin', 'X-Fastly-Request-ID': 'd906125f32727ad3626beec774ddc49c27e7c83d', 'Expires': 'Tue, 12 Nov 2024 08:08:09 GMT', 'Source-Age': '70'}
RESPONSE SIZE: 1862658 bytes

=== REQUEST ENDED ===
```
Although `104.21.88.162` appears to be a Cloudflare IP.
https://whois.domaintools.com/104.21.88.162

**Comment by matthuisman** [comment]
the xmls are stored on github and i.mjh.nz redirects to them. suspect github using fastly

**Comment by matthuisman** [comment]
its just gone down now

**Comment by telnetdoogie** [comment]
the good news is that allowed me to test the timeout and try/catch stuff without having to drop connections on my router :) A legit test!

```log
Received request: /
127.0.0.1 - - [12/Nov/2024 02:30:05] "GET / HTTP/1.1" 500 -
127.0.0.1 - - [12/Nov/2024 02:30:05] "GET / HTTP/1.1" 500 -
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 52780)
Error Encountered: Request to https://i.mjh.nz/SamsungTVPlus/.channels.json failed: HTTPSConnectionPool(host='i.mjh.nz', port=443): Read timed out.
Error Encountered: HTTPSConnectionPool(host='i.mjh.nz', port=443): Read timed out.
Traceback (most recent call last):
  File "C:\Users\jhobbs\Documents\CodingProjects\samsung-tvplus-for-channels\venv\lib\site-packages\urllib3\response.py", line 748, in _error_catcher
    yield
  File "C:\Users\jhobbs\Documents\CodingProjects\samsung-tvplus-for-channels\venv\lib\site-packages\urllib3\response.py", line 1206, in read_chunked
    self._update_chunk_length()
  File "C:\Users\jhobbs\Documents\CodingProjects\samsung-tvplus-for-channels\venv\lib\site-packages\urllib3\response.py", line 1125, in _update_chunk_length
    line = self._fp.fp.readline()  # type: ignore[union-attr]
  File "C:\Users\jhobbs\AppData\Local\Programs\Python\Python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\jhobbs\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\jhobbs\AppData\Local\Programs\Python\Python39\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\jhobbs\Documents\CodingProjects\samsung-tvplus-for-channels\venv\lib\site-packages\requests\models.py", line 820, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "C:\Users\jhobbs\Documents\CodingProjects\samsung-tvplus-for-channels\venv\lib\site-packages\urllib3\response.py", line 1057, in stream
    yield from self.read_chunked(amt, decode_content=decode_content)
  File "C:\Users\jhobbs\Documents\CodingProjects\samsung-tvplus-for-channels\venv\lib\site-packages\urllib3\response.py", line 1235, in read_chunked
    self._original_response.close()
  File "C:\Users\jhobbs\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\jhobbs\Documents\CodingProjects\samsung-tvplus-for-channels\venv\lib\site-packages\urllib3\response.py", line 753, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.") from e  # type: ignore[arg-type]
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='i.mjh.nz', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jhobbs\AppData\Local\Programs\Python\Python39\lib\socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Users\jhobbs\AppData\Local\Programs\Python\Python39\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\jhobbs\Documents\CodingProjects\samsung-tvplus-for-channels\app.py", line 26, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\jhobbs\AppData\Local\Programs\Python\Python39\lib\socketserver.py", line 747, in __init__
    self.handle()
  File "C:\Users\jhobbs\AppData\Local\Programs\Python\Python39\lib\http\server.py", line 427, in handle
    self.handle_one_request()
  File "C:\Users\jhobbs\AppData\Local\Programs\Python\Python39\lib\http\server.py", line 415, in handle_one_request
    method()
  File "C:\Users\jhobbs\Documents\CodingProjects\samsung-tvplus-for-channels\app.py", line 62, in do_GET
    self._error(e)
  File "C:\Users\jhobbs\Documents\CodingProjects\samsung-tvplus-for-channels\app.py", line 60, in do_GET
    routes[func]()
  File "C:\Users\jhobbs\Documents\CodingProjects\samsung-tvplus-for-channels\app.py", line 178, in _status
    all_channels = self._load_channels()
  File "C:\Users\jhobbs\Documents\CodingProjects\samsung-tvplus-for-channels\app.py", line 171, in _load_channels
    self._error(f'Request to {APP_URL} failed: {err}')
  File "C:\Users\jhobbs\Documents\CodingProjects\samsung-tvplus-for-channels\app.py", line 165, in _load_channels
    resp = requests.get(APP_URL, timeout=(CONNECT_TIMEOUT, READ_TIMEOUT))
  File "C:\Users\jhobbs\Documents\CodingProjects\samsung-tvplus-for-channels\venv\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\jhobbs\Documents\CodingProjects\samsung-tvplus-for-channels\venv\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\jhobbs\Documents\CodingProjects\samsung-tvplus-for-channels\venv\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\jhobbs\Documents\CodingProjects\samsung-tvplus-for-channels\venv\lib\site-packages\requests\sessions.py", line 746, in send
    r.content
  File "C:\Users\jhobbs\Documents\CodingProjects\samsung-tvplus-for-channels\venv\lib\site-packages\requests\models.py", line 902, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
  File "C:\Users\jhobbs\Documents\CodingProjects\samsung-tvplus-for-channels\venv\lib\site-packages\requests\models.py", line 826, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='i.mjh.nz', port=443): Read timed out.
----------------------------------------
```

**Comment by stewartcampbell** [comment]
I'm ok here. Pulled both the Json and .gz right now.

**Comment by matthuisman** [comment]
BAD:
![image](https://github.com/user-attachments/assets/a0e7a372-ed29-4ad8-b206-4332099d44f8)

What CF ray do you guys hit when downloading https://i.mjh.nz/PlutoTV/.channels.json

**Comment by matthuisman** [comment]
another json on same server was fine throughout
![image](https://github.com/user-attachments/assets/87b7e68d-8e75-470f-a71d-3814b9f19bad)

maybe the size? Or maybe the name?

**Comment by stewartcampbell** [comment]
Some inconsistent WAF rule that thinks we are using path traversal to exfiltrate dot files?

**Comment by matthuisman** [comment]
ok, so not a specific ray issue.
I was using .app.json for quite awhile without issues..
hmmm

**Comment by matthuisman** [comment]
going to create a few different filenames and start uptime jobs on those
![image](https://github.com/user-attachments/assets/f4661cba-9d15-4ce3-a464-30e5ff9036ce)
(yes, i cbf just copying them haha)

**Comment by telnetdoogie** [comment]
From the reports in CF are you able to see when CF cache expires and requests from origin? Does this happen right after retrieving from origin or is it just random?

**Comment by telnetdoogie** [comment]
> maybe the size? Or maybe the name?

This is an interesting proposition... since the name is unusual here and it looks like it's only happening on the `.name` sources

**Comment by stewartcampbell** [comment]
Anything in the security events section?

https://developers.cloudflare.com/waf/analytics/security-events/

I don't have the CF paid plan but can see all my custom rule blocks in there.

**Comment by matthuisman** [comment]
down again

**Comment by matthuisman** [comment]
again, xml are on github not CF cache so not really a good comparison at all. CF is just serving the 302 for them and thats it

**Comment by matthuisman** [comment]
ok, new files now live so can uptime those and see if any difference
![image](https://github.com/user-attachments/assets/ee23b4be-3eb3-4cdb-9b77-a75f7b979b0a)

**Comment by matthuisman** [comment]
@telnetdoogie it happens when its getting it from cache.
It caches for an hour on CF. So only 1 request per hour goes to origin

**Comment by matthuisman** [comment]
we went down at 2024-11-12 21:20:09 then again at 2024-11-12 22:03:16
43mins between
If its a trend, we should see another downtime around 46mins past this hour

**Comment by matthuisman** [comment]
down again now
And the different names didn't help :(
![image](https://github.com/user-attachments/assets/5efec175-3d6f-4428-9643-a0c9bf1963d1)

**Comment by stewartcampbell** [comment]
Oh I've read complaints about speedbrain beta. Mostly from dynamic sites, but you never know.

**Comment by matthuisman** [comment]
ive made one of those urls bypass the cache and will see if it behaves differently.
Also basically turned off cloudflare security on the i.mjh.nz

**Comment by matthuisman** [comment]
It's been an hour without downtime. New record. Fingers crossed 🤞

**Comment by stewartcampbell** [comment]
I've been hitting it every minute for over an hour myself, with no issues :)

**Comment by matthuisman** [comment]
Even the file not going via cache has also gone down. Hmm

**Comment by matthuisman** [comment]
have opened an issue on cloudflare forums:
https://community.cloudflare.com/t/extrememly-slow-performance-every-30-60mins-over-the-last-3-4-days/735831

**Comment by matthuisman** [comment]
it probably help if anyone who hits issues create account and +1 or upvote or comment or something to get it visible :)

**Comment by telnetdoogie** [comment]
Done and Done

**Comment by matthuisman** [comment]
ok. no responses and still getting so much timeouts.

What I have done just now is move the .json.gz's onto github and just redirecting to those.
Its slightly slower, but won't have the downtime at least :)

Ill continue to monitor the .json (no .gz) to see when that gets fixed

Ill release the new container which uses the .gz

**Comment by matthuisman** [comment]
new docker image now live

**Comment by stewartcampbell** [comment]
Nice one.

Another couple of thoughts:

* does the expires header in the response match when the downtime occurs?
* Does the ETag header change before and after downtime?

Looking back at my previous response with headers etc, the max-age header is set to 3600, matching your hourly interruption, so it seems very likely some cache config issue.

I looked through https://developers.cloudflare.com/cache/concepts/cache-control/#examples and can see a couple options to try in the server responses:

Cache-Control: public, max-age=3600, stale-if-error=3600

or

Cache-Control: max-age=600, stale-while-revalidate=3600

or possibly use both to test.

If either of these make a difference you should see some change in the length of time before errors, assuming they happen at all.

**Comment by stewartcampbell** [comment]
Although this post says they don't work...

https://community.cloudflare.com/t/stale-while-revalidate-does-not-work-at-all/578371

But it does point towards https://developers.cloudflare.com/cache/concepts/cdn-cache-control/ which has other CF specific headers you could try.

**Comment by matthuisman** [comment]
here are headers:
BAD:
![bad](https://github.com/user-attachments/assets/37a49525-b92f-444e-b465-09e3dcaa7930)
GOOD:
![good](https://github.com/user-attachments/assets/7d565221-30b9-410d-ab34-1c9d6bb31f43)

Same ETAG.
The CF-Ray does change

You can see they are both coming from cache. and not near the end of cache either.
The Age is also incremented the correct amount between them.

I have tried with cache off (they get served as DYNAMIC) and the issue still happens.

I just set up a new subdomain in CF with CF proxy off
Everything else the same. nginx simply listens to both domains.
And... the job not going via CF is fine.

**Comment by stewartcampbell** [comment]
I see `zstd` encoding used for the file. Is that header coming from your server?

I see a few posts with people having issues with it:

- https://community.cloudflare.com/t/intermittent-and-random-failed-to-load-resource-net-err-quic-protocol-error/676273 
- https://community.cloudflare.com/t/add-support-for-zstd-as-a-content-encoding/604123
- https://community.cloudflare.com/t/zstd-empty/728017/2

If this is coming from CF, then possibly you need to decompress first. This was AI generated as I am short on time and cant test but you get the idea:

```
response = requests.get(APP_URL)
content = response.content

if response.headers.get('Content-Encoding') == 'zstd':
    print("Found zstd encoding, decompressing...")
    import zstandard
    dctx = zstandard.ZstdDecompressor()
    content = dctx.decompress(content)
    print("Decompression complete")

all_channels = json.loads(content)['regions']
```

**Comment by matthuisman** [comment]
With the latest docker?
The CF issue is still there, it's just that I've worked around it in latest container

**Comment by telnetdoogie** [comment]
yeah, latest docker.

**Comment by matthuisman** [comment]
> yeah, latest docker.

Great. That is expected due to the .gz file no longer being hosted on CF. I'm still chasing the issues with CF

**Comment by matthuisman** [comment]
just noticed no downtime since 2:45am this morning!! 
Maybe CF has finally fixed the issue

**Comment by matthuisman** [comment]
still looking good!
1 week graph:
![image](https://github.com/user-attachments/assets/a3b9b3b8-b52a-4d66-bf65-c1eab37b47a6)

**Comment by telnetdoogie** [comment]
Did you hear anything from the CF folks? This is good news by the looks of it, but it's a bit worrying that it's just a fix without some known intervention...

**Comment by matthuisman** [comment]
Never heard anything. 🤔
