### ISSUE TITLE
python errors in most recent docker 

### ISSUE THREAD

**Issue by warrentc3** [matthuisman/samsung-tvplus-for-channels#2]
----------------------------------------
192.168.245.101 - - [22/Nov/2021 19:17:39] "GET /playlist.m3u HTTP/1.1" 500 -
----------------------------------------
Exception happened during processing of request from ('192.168.245.101', 58600)
Traceback (most recent call last):
  File "./app.py", line 46, in do_GET
    routes[func]()
  File "./app.py", line 86, in _playlist
    self.wfile.write(f'#EXTINF:-1 channel-id="{channel_id}" tvg-id="{key}" tvg-logo="{logo}" group-title="{group}"{chno},{name}\n{url}\n'.encode('utf8'))
  File "/usr/local/lib/python3.8/socketserver.py", line 826, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "./app.py", line 21, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "./app.py", line 48, in do_GET
    self._error(e)
  File "./app.py", line 25, in _error
    self.end_headers()
  File "/usr/local/lib/python3.8/http/server.py", line 529, in end_headers
    self.flush_headers()
  File "/usr/local/lib/python3.8/http/server.py", line 533, in flush_headers
    self.wfile.write(b"".join(self._headers_buffer))
  File "/usr/local/lib/python3.8/socketserver.py", line 826, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe

**Comment by matthuisman** [comment]
oops - i had forgot to send the headers before the content.
Should be fixed now. Please try pull latest docker image and test.
please close this issue if solved.
