### ISSUE TITLE
guide data

### ISSUE THREAD

**Issue by warrentc3** [matthuisman/samsung-tvplus-for-channels#5]
ChannelsDVR pulling m3u/XML fails.

----------------------------------------
192.168.245.99 - - [17/Nov/2022 15:12:01] "GET /playlist.m3u HTTP/1.1" 500 -
----------------------------------------
Exception happened during processing of request from ('192.168.245.99', 34760)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "./app.py", line 21, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "./app.py", line 48, in do_GET
    self._error(e)
  File "./app.py", line 46, in do_GET
    routes[func]()
  File "./app.py", line 58, in _playlist
    channels = regions[REGION].get('channels', {})
KeyError: 'us'

**Comment by matthuisman** [comment]
closing as will respond on https://github.com/matthuisman/samsung-tvplus-for-channels/issues/6
